#' kaixisHW4.
#'
#' @name kaixisHW4
#' @docType package
#' @author Kaixi Song
#' @import Rcpp
#' @importFrom Rcpp evalCpp
#' @useDynLib kaixisHW4
#' 
#' 
#' 
#' This function implement a Viterbi algorithm, given obeserved outcomes, transition and emission
#' matrices, and initial probabilities. 
#'
#'@param obs an m*n matrix representing probability from a given state to an observed outcome. 
#'@param theta a parameter which determines transition probability between states. 
#'@param ts a vector contains time point
#'
#'@return a vector represent the path that can lead to maximum likelihood
#'

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ctmcViterbi <- function(ts, theta, obs) {
  .Call('_kaixisHW4_ctmcViterbi', PACKAGE = 'kaixisHW4', ts, theta, obs)
}


#' This function implement a Viterbi algorithm, given obeserved outcomes, transition and emission
#' matrices, and initial probabilities. 
#'
#'@param obs an m*n matrix representing probability from a given state to an observed outcome. 
#'@param theta a parameter which determines transition probability between states. 
#'@param ts a vector contains time point
#'
#'@return matrix of conditioanl probability of each state given the observed outcomes.
#'

ctmcForwardBackward <- function(ts, theta, obs) {
    .Call('_kaixisHW4_ctmcForwardBackward', PACKAGE = 'kaixisHW4', ts, theta, obs)
}

